### ISSUE TITLE
Cannot run with Flutter 0.11.3

### ISSUE THREAD

**Issue by ngocdaothanh** [terrabythia/flutter_chromecast_example#2]
When I run `flutter packages get`, there's error:

```
Running "flutter packages get" in flutter_chromecast_example...      
The current Dart SDK version is 2.1.0-dev.9.3.flutter-9c07fb64c4.

Because flutter_chromecast_example depends on dart_chromecast from git which requires SDK version <2.0.0, version solving failed.
 
pub get failed (1)
```

**Comment by terrabythia** [comment]
I _think_ this was caused by the dependency cli_util of dart_chromecast, but unfortunately I can't test it at this moment myself. 

I did update the version number of the dependency, so you could try it again now.

Will try it myself too when I have the chanche.

**Comment by ngocdaothanh** [comment]
I've tried, and I think you need to add this to pubspec.yaml of dart_chromecast and flutter_mdns_plugin:

```
environment:
  sdk: '>=2.0.0 <3.0.0'
```

------------

I've tried by cloning dart_chromecast and flutter_mdns_plugin, and modified pubspec.yaml of flutter_chromecast_example like this:

```
  flutter_mdns_plugin:
    #git: https://github.com/terrabythia/flutter_mdns_plugin.git
    path: ../flutter_mdns_plugin
  dart_chromecast:
    #git: https://github.com/terrabythia/dart_chromecast.git
    path: ../dart_chromecast
```
